<?php
/**
 * Created by PhpStorm.
 * User: 老王专用
 * Date: 2019/4/14
 * Time: 13:03
 */

namespace app\exception;


use Exception;
use think\exception\Handle;
use think\Log;

class ExceptionHandle extends Handle
{
    private $code;
    private $msg;
    private $errorCode;
    public function render(Exception $e)
    {
        if($e instanceof BaseException){
            $this->code = $e->code;
            $this->msg = $e->msg;
            $this->errorCode = $e->errorCode;
        }else{
            if(config('app_debug')){
                return parent::render($e);
            }
            $this->code = 500;
            $this->msg = "服务器内部错误，无可奉告";
            $this->errorCode = 999;
            $this->recordErrorLog($e);
        }
        $result = [
            'error_code' => $this->errorCode,
            'msg' => $this->msg,
            'request_url' => request()->url(),
        ];
        return json($result,$this->code); // TODO: Change the autogenerated stub
    }
    protected function recordErrorLog(Exception $e){
        Log::init([
            'type'  => 'file',
            'path'  => LOG_PATH,
            'level' => ['error'],
        ]);
        Log::record($e->getMessage(),'error');
    }

}